
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Oct  9 2025 12:58:24 IST (Oct  9 2025 07:28:24 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, we, COUNT);
  input clk, rst, we;
  output [3:0] COUNT;
  wire clk, rst, we;
  wire [3:0] COUNT;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  DFFQX1 \COUNT_reg[3] (.CK (clk), .D (n_15), .Q (COUNT[3]));
  DFFQX1 \COUNT_reg[2] (.CK (clk), .D (n_14), .Q (COUNT[2]));
  AO22XL g298__2398(.A0 (n_13), .A1 (n_11), .B0 (n_12), .B1 (n_10), .Y
       (n_15));
  AO22X1 g301__5107(.A0 (n_13), .A1 (n_7), .B0 (n_12), .B1 (n_6), .Y
       (n_14));
  OAI21X1 g300__6260(.A0 (COUNT[3]), .A1 (n_8), .B0 (n_9), .Y (n_11));
  SDFFQX1 \COUNT_reg[1] (.CK (clk), .D (n_12), .SI (n_13), .SE (n_4),
       .Q (COUNT[1]));
  XOR2XL g302__4319(.A (n_1), .B (COUNT[3]), .Y (n_10));
  NAND2XL g304__8428(.A (COUNT[3]), .B (n_8), .Y (n_9));
  OAI21XL g305__5526(.A0 (n_3), .A1 (n_5), .B0 (n_8), .Y (n_7));
  MXI2XL g306__6783(.A (COUNT[2]), .B (n_5), .S0 (n_2), .Y (n_6));
  NAND2BX1 g307__3680(.AN (n_3), .B (n_2), .Y (n_4));
  DFFQX1 \COUNT_reg[0] (.CK (clk), .D (n_0), .Q (COUNT[0]));
  NOR2XL g309__1617(.A (n_5), .B (n_2), .Y (n_1));
  NAND2XL g310__2802(.A (n_5), .B (n_3), .Y (n_8));
  NOR2XL g313__1705(.A (rst), .B (COUNT[0]), .Y (n_0));
  NOR2XL g312__5122(.A (COUNT[1]), .B (COUNT[0]), .Y (n_3));
  NOR2XL g314__8246(.A (we), .B (rst), .Y (n_13));
  NAND2XL g315__7098(.A (COUNT[1]), .B (COUNT[0]), .Y (n_2));
  NOR2BXL g311__6131(.AN (we), .B (rst), .Y (n_12));
  CLKINVX1 g316(.A (COUNT[2]), .Y (n_5));
endmodule

